spring.datasource.url=jdbc:postgresql://db:5432/bolt_clientes
spring.datasource.username=bolt
spring.datasource.password=bolt123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
server.port=8080
